### ISSUE TITLE
action fail된 job 보수 필요

### ISSUE THREAD

**Issue by dev-bearabbit** [LOPES-HUFS/KBO_data#54]
현재 자동으로 데이터를 크롤링하여 데이터베이스에 저장하는 Job이 일부 정상 작동하지 않습니다.
해야 할 일은 다음과 같습니다.

- workflow troubleshooting
- 실패한 날들에 대한 데이터 수동으로 DB에 입력

**Comment by dialektike** [comment]
오늘 경기 스케줄 정리 할 때 더블 해더 경기를 제대로 처리하지 못 하고 있었습니다.
이를 수정합니다. 정상적적으로 작동하면 이 이슈는 닫겠습니다.
 
https://github.com/LOPES-HUFS/KBO_data/commit/cbb50e58cba78c61f8b14dcd7be84046a04e06f9

**Comment by dev-bearabbit** [comment]
workflow troubleshooting 완료 / 정상 작동 확인

**Comment by dev-bearabbit** [comment]
23일 데이터 수동 입력: 잡은 정상적으로 진행되었으나 데이터를 가져오지 못함 (list index out of range) 에러 발생

**Comment by dialektike** [comment]
@Hyeonji-Ryu 에러가 발생하는 부분 다음 링크 참고해주세요! 아래를 로그입니다.

https://github.com/LOPES-HUFS/KBO_data/runs/3993234080?check_suite_focus=true

```
[{'idx': 20211024011, 'team': 'SSG', 'result': 0, 'i_1': 0, 'i_2': 0, 'i_3': 0, 'i_4': 1, 'i_5': 0, 'i_6': 0, 'i_7': 2, 'i_8': 0, 'i_9': 0, 'i_10': None, 'i_11': None, 'i_12': None, 'i_13': None, 'i_14': None, 'i_15': None, 'i_16': None, 'i_17': None, 'i_18': None, 'r': 3, 'h': 4, 'e': 1, 'b': 2, 'year': 2021, 'month': 10, 'day': 24, 'week': 6, 'home': '삼성', 'away': 'SSG', 'dbheader': 0}, {'idx': 20211024003, 'team': '삼성', 'result': 0, 'i_1': 0, 'i_2': 0, 'i_3': 0, 'i_4': 0, 'i_5': 0, 'i_6': 0, 'i_7': 0, 'i_8': 3, 'i_9': 0, 'i_10': None, 'i_11': None, 'i_12': None, 'i_13': None, 'i_14': None, 'i_15': None, 'i_16': None, 'i_17': None, 'i_18': None, 'r': 3, 'h': 7, 'e': 2, 'b': 5, 'year': 2021, 'month': 10, 'day': 24, 'week': 6, 'home': '삼성', 'away': 'SSG', 'dbheader': 0}, {'idx': 20211024105, 'team': 'LG', 'result': -1, 'i_1': 0, 'i_2': 0, 'i_3': 0, 'i_4': 0, 'i_5': 2, 'i_6': 0, 'i_7': 1, 'i_8': 0, 'i_9': 1, 'i_10': None, 'i_11': None, 'i_12': None, 'i_13': None, 'i_14': None, 'i_15': None, 'i_16': None, 'i_17': None, 'i_18': None, 'r': 4, 'h': 5, 'e': 2, 'b': 11, 'year': 2021, 'month': 10, 'day': 24, 'week': 6, 'home': '두산', 'away': 'LG', 'dbheader': 1}, {'idx': 20211024101, 'team': '두산', 'result': 1, 'i_1': 0, 'i_2': 2, 'i_3': 0, 'i_4': 0, 'i_5': 0, 'i_6': 2, 'i_7': 0, 'i_8': 0, 'i_9': 1, 'i_10': None, 'i_11': None, 'i_12': None, 'i_13': None, 'i_14': None, 'i_15': None, 'i_16': None, 'i_17': None, 'i_18': None, 'r': 5, 'h': 9, 'e': 0, 'b': 4, 'year': 2021, 'month': 10, 'day': 24, 'week': 6, 'home': '두산', 'away': 'LG', 'dbheader': 1}, {'idx': 20211024006, 'team': 'KIA', 'result': -1, 'i_1': 0, 'i_2': 0, 'i_3': 0, 'i_4': 0, 'i_5': 0, 'i_6': 1, 'i_7': 0, 'i_8': 0, 'i_9': '0', 'i_10': None, 'i_11': None, 'i_12': None, 'i_13': None, 'i_14': None, 'i_15': None, 'i_16': None, 'i_17': None, 'i_18': None, 'r': 1, 'h': 7, 'e': 1, 'b': 1, 'year': 2021, 'month': 10, 'day': 24, 'week': 6, 'home': 'NC', 'away': 'KIA', 'dbheader': 0}, {'idx': 20211024009, 'team': 'NC', 'result': 1, 'i_1': 0, 'i_2': 0, 'i_3': 1, 'i_4': 0, 'i_5': 0, 'i_6': 0, 'i_7': 3, 'i_8': 0, 'i_9': None, 'i_10': None, 'i_11': None, 'i_12': None, 'i_13': None, 'i_14': None, 'i_15': None, 'i_16': None, 'i_17': None, 'i_18': None, 'r': 4, 'h': 8, 'e': 2, 'b': 4, 'year': 2021, 'month': 10, 'day': 24, 'week': 6, 'home': 'NC', 'away': 'KIA', 'dbheader': 0}, {'idx': 20211024205, 'team': 'LG', 'result': 0, 'i_1': 3, 'i_2': 0, 'i_3': 0, 'i_4': 0, 'i_5': 0, 'i_6': 0, 'i_7': 0, 'i_8': 0, 'i_9': 0, 'i_10': None, 'i_11': None, 'i_12': None, 'i_13': None, 'i_14': None, 'i_15': None, 'i_16': None, 'i_17': None, 'i_18': None, 'r': 3, 'h': 5, 'e': 2, 'b': 4, 'year': 2021, 'month': 10, 'day': 24, 'week': 6, 'home': '두산', 'away': 'LG', 'dbheader': 2}, {'idx': 20211024201, 'team': '두산', 'result': 0, 'i_1': 1, 'i_2': 0, 'i_3': 0, 'i_4': 0, 'i_5': 1, 'i_6': 0, 'i_7': 0, 'i_8': 0, 'i_9': 1, 'i_10': None, 'i_11': None, 'i_12': None, 'i_13': None, 'i_14': None, 'i_15': None, 'i_16': None, 'i_17': None, 'i_18': None, 'r': 3, 'h': 7, 'e': 1, 'b': 7, 'year': 2021, 'month': 10, 'day': 24, 'week': 6, 'home': '두산', 'away': 'LG', 'dbheader': 2}]
36
table columns keys:['idx', 'team', 'result', 'i_1', 'i_2', 'i_3', 'i_4', 'i_5', 'i_6', 'i_7', 'i_8', 'i_9', 'i_10', 'i_11', 'i_12', 'i_13', 'i_14', 'i_15', 'i_16', 'i_17', 'i_18', 'r', 'h', 'e', 'b', 'year', 'month', 'day', 'week', 'home', 'away', 'dbheader']
37
Traceback (most recent call last):
38
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1752, in _execute_context
39
    cursor, statement, parameters, context
40
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 197, in do_executemany
41
    rowcount = cursor.executemany(statement, parameters)
42
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pymysql/cursors.py", line 179, in executemany
43
    self._get_db().encoding,
44
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pymysql/cursors.py", line 211, in _do_execute_many
45
    rows += self.execute(sql + postfix)
46
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
47
    result = self._query(query)
48
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
49
    conn.query(q)
50
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
51
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
52
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pymysql/connections.py", line 775, in _read_query_result
53
    result.read()
54
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pymysql/connections.py", line 1156, in read
55
    first_packet = self.connection._read_packet()
56
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pymysql/connections.py", line 725, in _read_packet
57
    packet.raise_for_error()
58
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pymysql/protocol.py", line 221, in raise_for_error
59
    err.raise_mysql_exception(self._data)
60
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
61
    raise errorclass(errno, errval)
62
pymysql.err.IntegrityError: (1062, "Duplicate entry '20211024011' for key 'PRIMARY'")
63

64
The above exception was the direct cause of the following exception:
65

66
Traceback (most recent call last):
67
  File "for_actions.py", line 70, in <module>
68
    result_proxy = connection.execute(query, temp_scoreboards)
69
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1263, in execute
70
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
71
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 324, in _execute_on_connection
72
    self, multiparams, params, execution_options
73
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1462, in _execute_clauseelement
74
    cache_hit=cache_hit,
75
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1815, in _execute_context
76
    e, statement, parameters, cursor, context
77
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1996, in _handle_dbapi_exception
78
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
79
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
80
    raise exception
81
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1752, in _execute_context
82
    cursor, statement, parameters, context
83
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 197, in do_executemany
84
    rowcount = cursor.executemany(statement, parameters)
85
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pymysql/cursors.py", line 179, in executemany
86
    self._get_db().encoding,
87
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pymysql/cursors.py", line 211, in _do_execute_many
88
    rows += self.execute(sql + postfix)
89
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
90
    result = self._query(query)
91
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
92
    conn.query(q)
93
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
94
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
95
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pymysql/connections.py", line 775, in _read_query_result
96
    result.read()
97
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pymysql/connections.py", line 1156, in read
98
    first_packet = self.connection._read_packet()
99
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pymysql/connections.py", line 725, in _read_packet
100
    packet.raise_for_error()
101
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pymysql/protocol.py", line 221, in raise_for_error
102
    err.raise_mysql_exception(self._data)
103
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
104
    raise errorclass(errno, errval)
105
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '20211024011' for key 'PRIMARY'")
106
[SQL: INSERT INTO scoreboard (idx, team, result, i_1, i_2, i_3, i_4, i_5, i_6, i_7, i_8, i_9, i_10, i_11, i_12, i_13, i_14, i_15, i_16, i_17, i_18, r, h, e, b, year, month, day, week, home, away, dbheader) VALUES (%(idx)s, %(team)s, %(result)s, %(i_1)s, %(i_2)s, %(i_3)s, %(i_4)s, %(i_5)s, %(i_6)s, %(i_7)s, %(i_8)s, %(i_9)s, %(i_10)s, %(i_11)s, %(i_12)s, %(i_13)s, %(i_14)s, %(i_15)s, %(i_16)s, %(i_17)s, %(i_18)s, %(r)s, %(h)s, %(e)s, %(b)s, %(year)s, %(month)s, %(day)s, %(week)s, %(home)s, %(away)s, %(dbheader)s)]
107
[parameters: ({'idx': 20211024011, 'team': 'SSG', 'result': 0, 'i_1': 0, 'i_2': 0, 'i_3': 0, 'i_4': 1, 'i_5': 0, 'i_6': 0, 'i_7': 2, 'i_8': 0, 'i_9': 0, 'i_10': None, 'i_11': None, 'i_12': None, 'i_13': None, 'i_14': None, 'i_15': None, 'i_16': None, 'i_17': None, 'i_18': None, 'r': 3, 'h': 4, 'e': 1, 'b': 2, 'year': 2021, 'month': 10, 'day': 24, 'week': 6, 'home': '삼성', 'away': 'SSG', 'dbheader': 0}, {'idx': 20211024003, 'team': '삼성', 'result': 0, 'i_1': 0, 'i_2': 0, 'i_3': 0, 'i_4': 0, 'i_5': 0, 'i_6': 0, 'i_7': 0, 'i_8': 3, 'i_9': 0, 'i_10': None, 'i_11': None, 'i_12': None, 'i_13': None, 'i_14': None, 'i_15': None, 'i_16': None, 'i_17': None, 'i_18': None, 'r': 3, 'h': 7, 'e': 2, 'b': 5, 'year': 2021, 'month': 10, 'day': 24, 'week': 6, 'home': '삼성', 'away': 'SSG', 'dbheader': 0}, {'idx': 20211024105, 'team': 'LG', 'result': -1, 'i_1': 0, 'i_2': 0, 'i_3': 0, 'i_4': 0, 'i_5': 2, 'i_6': 0, 'i_7': 1, 'i_8': 0, 'i_9': 1, 'i_10': None, 'i_11': None, 'i_12': None, 'i_13': None, 'i_14': None, 'i_15': None, 'i_16': None, 'i_17': None, 'i_18': None, 'r': 4, 'h': 5, 'e': 2, 'b': 11, 'year': 2021, 'month': 10, 'day': 24, 'week': 6, 'home': '두산', 'away': 'LG', 'dbheader': 1}, {'idx': 20211024101, 'team': '두산', 'result': 1, 'i_1': 0, 'i_2': 2, 'i_3': 0, 'i_4': 0, 'i_5': 0, 'i_6': 2, 'i_7': 0, 'i_8': 0, 'i_9': 1, 'i_10': None, 'i_11': None, 'i_12': None, 'i_13': None, 'i_14': None, 'i_15': None, 'i_16': None, 'i_17': None, 'i_18': None, 'r': 5, 'h': 9, 'e': 0, 'b': 4, 'year': 2021, 'month': 10, 'day': 24, 'week': 6, 'home': '두산', 'away': 'LG', 'dbheader': 1}, {'idx': 20211024006, 'team': 'KIA', 'result': -1, 'i_1': 0, 'i_2': 0, 'i_3': 0, 'i_4': 0, 'i_5': 0, 'i_6': 1, 'i_7': 0, 'i_8': 0, 'i_9': '0', 'i_10': None, 'i_11': None, 'i_12': None, 'i_13': None, 'i_14': None, 'i_15': None, 'i_16': None, 'i_17': None, 'i_18': None, 'r': 1, 'h': 7, 'e': 1, 'b': 1, 'year': 2021, 'month': 10, 'day': 24, 'week': 6, 'home': 'NC', 'away': 'KIA', 'dbheader': 0}, {'idx': 20211024009, 'team': 'NC', 'result': 1, 'i_1': 0, 'i_2': 0, 'i_3': 1, 'i_4': 0, 'i_5': 0, 'i_6': 0, 'i_7': 3, 'i_8': 0, 'i_9': None, 'i_10': None, 'i_11': None, 'i_12': None, 'i_13': None, 'i_14': None, 'i_15': None, 'i_16': None, 'i_17': None, 'i_18': None, 'r': 4, 'h': 8, 'e': 2, 'b': 4, 'year': 2021, 'month': 10, 'day': 24, 'week': 6, 'home': 'NC', 'away': 'KIA', 'dbheader': 0}, {'idx': 20211024205, 'team': 'LG', 'result': 0, 'i_1': 3, 'i_2': 0, 'i_3': 0, 'i_4': 0, 'i_5': 0, 'i_6': 0, 'i_7': 0, 'i_8': 0, 'i_9': 0, 'i_10': None, 'i_11': None, 'i_12': None, 'i_13': None, 'i_14': None, 'i_15': None, 'i_16': None, 'i_17': None, 'i_18': None, 'r': 3, 'h': 5, 'e': 2, 'b': 4, 'year': 2021, 'month': 10, 'day': 24, 'week': 6, 'home': '두산', 'away': 'LG', 'dbheader': 2}, {'idx': 20211024201, 'team': '두산', 'result': 0, 'i_1': 1, 'i_2': 0, 'i_3': 0, 'i_4': 0, 'i_5': 1, 'i_6': 0, 'i_7': 0, 'i_8': 0, 'i_9': 1, 'i_10': None, 'i_11': None, 'i_12': None, 'i_13': None, 'i_14': None, 'i_15': None, 'i_16': None, 'i_17': None, 'i_18': None, 'r': 3, 'h': 7, 'e': 1, 'b': 7, 'year': 2021, 'month': 10, 'day': 24, 'week': 6, 'home': '두산', 'away': 'LG', 'dbheader': 2})]
108
(Background on this error at: https://sqlalche.me/e/14/gkpj)
109
Error: Process completed with exit code 1.
```

**Comment by dialektike** [comment]
@Hyeonji-Ryu 35과 36번 줄이 나온다는 것은 자료가 수집되었다는 것입니다.

**Comment by dialektike** [comment]
@Hyeonji-Ryu (list index out of range) 에러가 발생하는 위치를 알려주세요.

**Comment by dev-bearabbit** [comment]
@dialektike  현재 23일 데이터가 DB에 적재되어 있기에 23일 잡 실행 시 기본키 에러가 발생합니다. 24일 또한 일부 list index out of range가 발생하다가 현재 정상작동 되는 것을 확인했습니다.

**Comment by dev-bearabbit** [comment]
@dialektike  동일 경기를 중복 크롤링 합니다 (https://github.com/LOPES-HUFS/KBO_data/runs/4004687574?check_suite_focus=true) 확인 부탁드립니당

**Comment by dialektike** [comment]
> @dialektike 동일 경기를 중복 크롤링 합니다 (https://github.com/LOPES-HUFS/KBO_data/runs/4004687574?check_suite_focus=true) 확인 부탁드립니당

@Hyeonji-Ryu  이 문제를 해결했습니다. 동일 경기가 중복되지 않을 것입니다.

Actions에서 KBO today's schedule 을 살펴보세요

**Comment by dialektike** [comment]
@Hyeonji-Ryu 아래 수정으로 이 문제로 해결될 것 같습니다.

https://github.com/LOPES-HUFS/KBO_data/commit/c13c35fee86464b7db4c9abddb8c92532ed4cbdc
